// client/src/features/corporativo/Indicadores/IndicadoresComparativosPage.jsx import React from "react" ;
export default function IndicadoresComparativosPage( )
{
return ( <div className= "neo card p 4 md:p 5 spacey 4 " > <header className= "flex items center justify between gap 3 " > <div> <h1 className= "text base md:text lg font semibold" > Comparativos de indicadores < /h1 > <p className= "text xs md:text sm text slate 4 0 0 " > Comparaci?n por a鐢?o , pa?s , zona y tipo de activo (propiedades, restaurantes, negocios en USA)
. < /p> < /div> < /header> <div className= "grid gap 4 md:grid cols [minmax( 0 , 2fr)
_minmax( 0 , 1 . 1fr)
] " > <div className= "spacey 3 " > <div className= "flex flex wrap items center gap 2 text xs" > <span className= "font semibold text slate 3 0 0 " >Filtros r?pidos: < /span> <button className= "px 2 . 5 py 1 rounded full bg slate 8 0 0 text slate 1 0 0 text xs border border slate 7 0 0 " > 閼?ltimos 1 2 meses < /button> <button className= "px 2 . 5 py 1 rounded full bg slate 9 0 0 text slate 3 0 0 text xs border border slate 7 0 0 / 8 0 " > El Salvador vs USA < /button> <button className= "px 2 . 5 py 1 rounded full bg slate 9 0 0 text slate 3 0 0 text xs border border slate 7 0 0 / 8 0 " > Propiedades vs Restaurantes < /button> < /div> <div className= "mt 2 h 5 6 rounded xl border border [var( border)
] / 8 0 bg [var( panel)
] / 4 0 flex items center justify center text xs md:text sm text slate 4 0 0 " > Aqu? ir? un gr?fico comparativo (l?neas / columnas)
de producci?n y margen entre pa?ses, zonas o tipos de activos . < /div> < /div> <aside className= "spacey 3 text xs md:text sm" > <h2 className= "font semibold text slate 2 0 0 " > Lectura recomendada < /h2 > <p className= "text slate 4 0 0 " > Usa este panel para responder preguntas como: < /p> <ul className= "list disc list inside spacey 1 text slate 3 0 0 " > <li> ?Cu?l zona crece m?s r?pido: Lourdes Col?n o Los 閼?ngeles? < /li> <li> ?Los restaurantes en Chaparral est?n mejorando su margen frente a las propiedades? < /li> <li> ?Qu閼? tan vol?til es la producci?n mensual por negocio o propiedad? < /li> < /ul> <p className= "mt 3 text slate 4 0 0 " > M?s adelante, este panel consumir? datos reales desde el m?dulo de <span className= "font semibold" > Transacciones< /span> y de <span className= "font semibold" > Proyectos< /span> para graficar tendencias. < /p> < /aside> < /div> < /div> )
;
}